---
- name: Ensure usergroups exist
  group:
    name: "{{item}}"
    state: present
  with_items:
    "{{usergroups}}"

- name: Create users
  user:
    name: "{{item.name}}"
    groups: "{{item.groups}}"
    append: yes
  with_items:
    "{{users}}"

- name: Create personal folders for users
  file:
    path: /{{zfs.poolName}}/personal/{{item.name}}
    state: directory
    owner: "{{item.name}}"
    group: "{{item.name}}"
    mode: '700'
  with_items:
    - "{{users}}"

- name: Create backup folder for users
  file:
    path: /{{zfs.poolName}}/backup/{{item.name}}
    state: directory
    owner: "{{item.name}}"
    group: "{{item.name}}"
    mode: '700'
  with_items:
    - "{{users}}"

- name: Create shared folders
  file:
    path: "{{item.path}}"
    state: directory
    group: "{{shared_folders_group}}"
    mode: '771'
  with_items:
    - "{{shared_folders}}"